# -*- coding: utf-8 -*-

"""
xero

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from xero.api_helper import APIHelper
from xero.configuration import Server
from xero.controllers.base_controller import BaseController
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter
from xero.http.http_method_enum import HttpMethodEnum
from apimatic_core.authentication.multiple.single_auth import Single
from xero.exceptions.api_exception import APIException


class ContactGroupsController(BaseController):

    """A Controller to access Endpoints in the xero API."""
    def __init__(self, config):
        super(ContactGroupsController, self).__init__(config)

    def allows_you_to_retrieve_the_contact_id_and_name_of_all_the_contacts_in_a_contact_group(self,
                                                                                              where,
                                                                                              order,
                                                                                              xero_tenant_id):
        """Does a GET request to /ContactGroups.

        Args:
            where (str): Filter by an any element
            order (str): Order by an any element
            xero_tenant_id (str): (Required) Xero identifier for Tenant

        Returns:
            str: Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER_1)
            .path('/ContactGroups')
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                         .key('where')
                         .value(where))
            .query_param(Parameter()
                         .key('order')
                         .value(order))
            .header_param(Parameter()
                          .key('xero-tenant-id')
                          .value(xero_tenant_id))
            .auth(Single('oauth2'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
        ).execute()

    def allows_you_to_create_a_contact_group(self,
                                             xero_tenant_id,
                                             body):
        """Does a PUT request to /ContactGroups.

        Args:
            xero_tenant_id (str): (Required) Xero identifier for Tenant
            body (AllowsYouToCreateAContactGroupRequest): The request body
                parameter.

        Returns:
            str: Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER_1)
            .path('/ContactGroups')
            .http_method(HttpMethodEnum.PUT)
            .header_param(Parameter()
                          .key('xero-tenant-id')
                          .value(xero_tenant_id))
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('oauth2'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .local_error('400', 'Bad Request', APIException)
        ).execute()
